//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesTaxesCalculator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    public sealed partial class Taxes : global::System.Configuration.ApplicationSettingsBase {
        
        private static Taxes defaultInstance = ((Taxes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Taxes())));
        
        public static Taxes Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double BasicTaxRate {
            get {
                return ((double)(this["BasicTaxRate"]));
            }
            set {
                this["BasicTaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ExemptTaxRate {
            get {
                return ((double)(this["ExemptTaxRate"]));
            }
            set {
                this["ExemptTaxRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double ImportsTaxRate {
            get {
                return ((double)(this["ImportsTaxRate"]));
            }
            set {
                this["ImportsTaxRate"] = value;
            }
        }
    }
}
